class Autogenerated {
  String code;
  String message;
  List<Data> data;

  Autogenerated({this.code, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    message = json['message'];
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int userId;
  int mealType;
  double price;
  int diningStatus;
  int state;
  int quantity;
  int eaten_quantity;
  int mealstatId;
  String orderDate;
  int canteenID;
  int costType;
  int ticketNum;

  Data(
      {this.userId,
      this.mealType,
      this.price,
      this.diningStatus,
      this.state,
      this.quantity,
      this.eaten_quantity,
      this.mealstatId,
      this.orderDate,
      this.canteenID,
      this.costType,
      this.ticketNum}
    );

  Data.fromJson(Map<String, dynamic> json) {
    userId = json['user_id'];
    mealType = json['meal_type'];
    price = double.parse(json['price'].toString());
    diningStatus = json['dining_status'];
    state = json['state'];
    quantity = json['quantity'];
    eaten_quantity=json['eaten_quantity'];
    mealstatId = json['mealstat_id'];
    orderDate = json['order_date'];
    canteenID = json['canteen_id'];
    costType = json['cost_type'];
    ticketNum = json['ticket_num'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['user_id'] = this.userId;
    data['meal_type'] = this.mealType;
    data['price'] = this.price;
    data['dining_status'] = this.diningStatus;
    data['state'] = this.state;
    data['quantity'] = this.quantity;
    data['eaten_quantity']=this.eaten_quantity;
    data['mealstat_id'] = this.mealstatId;
    data['order_date'] = this.orderDate;
    data['canteen_id'] = this.canteenID;
    data['cost_type'] = this.costType;
    data['ticket_num'] = this.ticketNum;
    return data;
  }
}
