///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryBigModelDataSecondaryCategoryList {
/*
{
  "category_id": 1,
  "category_name": "猪肉"
} 
*/

  String categoryId;
  String categoryName;

  CategoryBigModelDataSecondaryCategoryList({
    this.categoryId,
    this.categoryName,
  });
  CategoryBigModelDataSecondaryCategoryList.fromJson(Map<String, dynamic> json) {
    categoryId = json["category_id"]?.toString();
    categoryName = json["category_name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["category_id"] = categoryId;
    data["category_name"] = categoryName;
    return data;
  }
}

class CategoryBigModelData {
/*
{
  "primary_category_id": 1,
  "primary_category_name": "肉类",
  "secondary_category_list": [
    {
      "category_id": 1,
      "category_name": "猪肉"
    }
  ]
} 
*/

  String primaryCategoryId;
  String primaryCategoryName;
  List<CategoryBigModelDataSecondaryCategoryList> secondaryCategoryList;

  CategoryBigModelData({
    this.primaryCategoryId,
    this.primaryCategoryName,
    this.secondaryCategoryList,
  });
  CategoryBigModelData.fromJson(Map<String, dynamic> json) {
    primaryCategoryId = json["primary_category_id"]?.toString();
    primaryCategoryName = json["primary_category_name"]?.toString();
    if (json["secondary_category_list"] != null) {
      var v = json["secondary_category_list"];
      var arr0 = List<CategoryBigModelDataSecondaryCategoryList>();
      v.forEach((v) {
        arr0.add(CategoryBigModelDataSecondaryCategoryList.fromJson(v));
      });
      secondaryCategoryList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["primary_category_id"] = primaryCategoryId;
    data["primary_category_name"] = primaryCategoryName;
    if (secondaryCategoryList != null) {
      var v = secondaryCategoryList;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["secondary_category_list"] = arr0;
    }
    return data;
  }
}

class CategoryBigModel {
/*
{
  "code": "0",
  "message": "success",
  "data": [
    {
      "primary_category_id": 1,
      "primary_category_name": "肉类",
      "secondary_category_list": [
        {
          "category_id": 1,
          "category_name": "猪肉"
        }
      ]
    }
  ]
} 
*/

  String code;
  String message;
  List<CategoryBigModelData> data;

  CategoryBigModel({
    this.code,
    this.message,
    this.data,
  });
  CategoryBigModel.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toString();
    message = json["message"]?.toString();
    if (json["data"] != null) {
      var v = json["data"];
      var arr0 = List<CategoryBigModelData>();
      if(v is String){
        arr0 = [];
      }else{
        v.forEach((v) {
          arr0.add(CategoryBigModelData.fromJson(v));
        });
      }
      data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data.toList();
    }
    return data;
  }
}
