///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class foodDetailsDataFoodComments {
/*
{
        "comment_id": 1,
        "comment_details": "味道还可以啊",
         "dish_score": 5,
         "create_time": "2019-10-31 09:17:19",
          "meal_type": 0,
          "order_date": "2020-01-01",
          "dish_id": "1",
          "user_id": "1201781965343297552"
}
*/
  int comment_id;
  double dish_score;
  String comment_details;
  String create_time;
  //modify by lilixia   2020-11-23
  String user_name;
  int meal_type;
  String order_date;
  String user_id;
  int mealstat_id_id;
  int dish_id;

  foodDetailsDataFoodComments({
    this.comment_id,
    this.dish_score,
    this.comment_details,
    this.create_time,
    //modify by lilixia   2020-11-23
    this.user_name,
    this.meal_type,
    this.order_date,
    this.user_id,
    this.mealstat_id_id,
    this.dish_id,
  });
  foodDetailsDataFoodComments.fromJson(Map<String, dynamic> json) {
    comment_id = json["comment_id"]?.toInt();
    dish_score = json["dish_score"]?.toDouble();
    comment_details = json["comment_details"]?.toString();
    create_time = json["create_time"]?.toString();
    //modify by lilixia   2020-11-23
    user_name = json["user_name"]?.toString();
    meal_type = json["meal_type"]?.toInt();
    order_date = json["order_date"]?.toString();
    user_id = json["user_id"]?.toString();
    mealstat_id_id=json["mealstat_id_id"]?.toInt();
    dish_id = json["dish_id"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["comment_id"] = comment_id;
    data["dish_score"] =dish_score ;
    data["comment_details"] = comment_details;
    //modify by lilixia   2020-11-23
    data["user_name"] = user_name;
    data["create_time"] =create_time ;
    data["meal_type"] = meal_type;
    data["order_date"] =order_date ;
    data["user_id"] = user_id;
    data["mealstat_id_id"]=mealstat_id_id;
    data["dish_id"] = dish_id;
    return data;
  }
}

class foodDetailsDataFoodInfo {
/*
{
  "dish_id": 1,
  "canteen_id": 1,
  "dish_name": "辣椒炒肉",
  "dish_desc": "湖南特色菜",
  "dish_flavor": "辣",
  "dish_price": 19.9,
  "dish_photo": [
    "/dish/image1.jpg"
  ],
  "create_time": 1572509281,
  "update_time": 1573701800,
  "dish_score": 0,
  "category": 1
}
*/

  int dishId;
  int canteenId;
  String dishName;
  String dishDesc;
  String dishFlavor;
  double dishPrice;
  List<String> dishPhoto;
  String createTime;
  String updateTime;
  double dishScore;
  int category;

  foodDetailsDataFoodInfo({
    this.dishId,
    this.canteenId,
    this.dishName,
    this.dishDesc,
    this.dishFlavor,
    this.dishPrice,
    this.dishPhoto,
    this.createTime,
    this.updateTime,
    this.dishScore,
    this.category,
  });
  foodDetailsDataFoodInfo.fromJson(Map<String, dynamic> json) {
    dishId = json["dish_id"]?.toInt();
    canteenId = json["canteen_id"]?.toInt();
    dishName = json["dish_name"]?.toString();
    dishDesc = json["dish_desc"]?.toString();
    dishFlavor = json["dish_flavor"]?.toString();
    dishPrice = json["dish_price"]?.toDouble();
    if (json["dish_photo"] != null) {
      var v = json["dish_photo"];
      var arr0 = List<String>();
      v.forEach((v) {
        arr0.add(v.toString());
      });
      dishPhoto = arr0;
    }
    createTime = json["create_time"]?.toString();
    updateTime = json["update_time"]?.toString();
    dishScore = json["dish_score"]?.toDouble();
    category = json["category_id"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dish_id"] = dishId;
    data["canteen_id"] = canteenId;
    data["dish_name"] = dishName;
    data["dish_desc"] = dishDesc;
    data["dish_flavor"] = dishFlavor;
    data["dish_price"] = dishPrice;
    if (dishPhoto != null) {
      var v = dishPhoto;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v);
      });
      data["dish_photo"] = arr0;
    }
    data["create_time"] = createTime;
    data["update_time"] = updateTime;
    data["dish_score"] = dishScore;
    data["category"] = category;
    return data;
  }
}

class foodDetailsData {
/*
{
  "foodInfo": {
    "dish_id": 1,
    "canteen_id": 1,
    "dish_name": "辣椒炒肉",
    "dish_desc": "湖南特色菜",
    "dish_flavor": "辣",
    "dish_price": 19.9,
    "dish_photo": [
      "/dish/image1.jpg"
    ],
    "create_time": 1572509281,
    "update_time": 1573701800,
    "dish_score": 0,
    "category": 1
  },
  "foodComments": [
    {
        "comment_id": 1,
        "comment_details": "味道还可以啊",
         "dish_score": 5,
         "create_time": "2019-10-31 09:17:19",
          "meal_type": 0,
          "order_date": "2020-01-01",
          "dish_id": "1",
          "user_id": "1201781965343297552"
    }
  ]
}
*/

  foodDetailsDataFoodInfo foodInfo;
  List<foodDetailsDataFoodComments> foodComments;

  foodDetailsData({
    this.foodInfo,
    this.foodComments,
  });
  foodDetailsData.fromJson(Map<String, dynamic> json) {
    foodInfo = json["foodInfo"] != null ? foodDetailsDataFoodInfo.fromJson(json["foodInfo"]) : null;
    if (json["foodComments"] != null) {
      var v = json["foodComments"];
      var arr0 = List<foodDetailsDataFoodComments>();
      v.forEach((v) {
        arr0.add(foodDetailsDataFoodComments.fromJson(v));
      });
      foodComments = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (foodInfo != null) {
      data["foodInfo"] = foodInfo.toJson();
    }
    if (foodComments != null) {
      var v = foodComments;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["foodComments"] = arr0;
    }
    return data;
  }
}

class foodDetails {
/*
{
  "code": "0",
  "message": "success",
  "data": {
    "foodInfo": {
      "dish_id": 1,
      "canteen_id": 1,
      "dish_name": "辣椒炒肉",
      "dish_desc": "湖南特色菜",
      "dish_flavor": "辣",
      "dish_price": 19.9,
      "dish_photo": [
        "/dish/image1.jpg"
      ],
      "create_time": 1572509281,
      "update_time": 1573701800,
      "dish_score": 0,
      "category": 1
    },
    "foodComments": [
      {
        "comment_id": 1,
        "comment_details": "味道还可以啊",
         "dish_score": 5,
         "create_time": "2019-10-31 09:17:19",
          "meal_type": 0,
          "order_date": "2020-01-01",
          "dish_id": "1",
          "user_id": "1201781965343297552"
      }
    ]
  }
}
*/

  String code;
  String message;
  foodDetailsData data;

  foodDetails({
    this.code,
    this.message,
    this.data,
  });
  foodDetails.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toString();
    message = json["message"]?.toString();
    data = json["data"] != null ? foodDetailsData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

