///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FoodDishModelDataFoodInfoList {
/*
{
  "dish_id": 3,
  "canteen_id": 1,
  "dish_name": "清炒丝瓜",
  "dish_desc": "湖南特色菜",
  "dish_flavor": "清淡",
  "dish_price": 20,
  "dish_photo": [
    "/dish/image3.jpg"
  ],
  "create_time": 1572510046,
  "update_time": 1573701800,
  "dish_score": 0,
  "category": 6
}
*/

  int dishId;
  int canteenId;
  String dishName;
  String dishDesc;
  String dishFlavor;
  int dishPrice;
  List<String> dishPhoto;
  int createTime;
  int updateTime;
  int dishScore;
  int category;

  FoodDishModelDataFoodInfoList({
    this.dishId,
    this.canteenId,
    this.dishName,
    this.dishDesc,
    this.dishFlavor,
    this.dishPrice,
    this.dishPhoto,
    this.createTime,
    this.updateTime,
    this.dishScore,
    this.category,
  });
  FoodDishModelDataFoodInfoList.fromJson(Map<String, dynamic> json) {
    dishId = json["dish_id"]?.toInt();
    canteenId = json["canteen_id"]?.toInt();
    dishName = json["dish_name"]?.toString();
    dishDesc = json["dish_desc"]?.toString();
    dishFlavor = json["dish_flavor"]?.toString();
    dishPrice = json["dish_price"]?.toInt();
    if (json["dish_photo"] != null) {
      var v = json["dish_photo"];
      var arr0 = List<String>();
      v.forEach((v) {
        arr0.add(v.toString());
      });
      dishPhoto = arr0;
    }
    createTime = json["create_time"]?.toInt();
    updateTime = json["update_time"]?.toInt();
    dishScore = json["dish_score"]?.toInt();
    category = json["category"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dish_id"] = dishId;
    data["canteen_id"] = canteenId;
    data["dish_name"] = dishName;
    data["dish_desc"] = dishDesc;
    data["dish_flavor"] = dishFlavor;
    data["dish_price"] = dishPrice;
    if (dishPhoto != null) {
      var v = dishPhoto;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v);
      });
      data["dish_photo"] = arr0;
    }
    data["create_time"] = createTime;
    data["update_time"] = updateTime;
    data["dish_score"] = dishScore;
    data["category"] = category;
    return data;
  }
}

class FoodDishModelData {
/*
{
  "foodInfoList": [
    {
      "dish_id": 3,
      "canteen_id": 1,
      "dish_name": "清炒丝瓜",
      "dish_desc": "湖南特色菜",
      "dish_flavor": "清淡",
      "dish_price": 20,
      "dish_photo": [
        "/dish/image3.jpg"
      ],
      "create_time": 1572510046,
      "update_time": 1573701800,
      "dish_score": 0,
      "category": 6
    }
  ]
}
*/

  List<FoodDishModelDataFoodInfoList> foodInfoList;

  FoodDishModelData({
    this.foodInfoList,
  });
  FoodDishModelData.fromJson(Map<String, dynamic> json) {
    if (json["foodInfoList"] != null) {
      var v = json["foodInfoList"];
      var arr0 = List<FoodDishModelDataFoodInfoList>();
      v.forEach((v) {
        arr0.add(FoodDishModelDataFoodInfoList.fromJson(v));
      });
      foodInfoList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (foodInfoList != null) {
      var v = foodInfoList;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["foodInfoList"] = arr0;
    }
    return data;
  }
}

class FoodDishModel {
/*
{
  "code": "0",
  "message": "success",
  "data": {
    "foodInfoList": [
      {
        "dish_id": 3,
        "canteen_id": 1,
        "dish_name": "清炒丝瓜",
        "dish_desc": "湖南特色菜",
        "dish_flavor": "清淡",
        "dish_price": 20,
        "dish_photo": [
          "/dish/image3.jpg"
        ],
        "create_time": 1572510046,
        "update_time": 1573701800,
        "dish_score": 0,
        "category": 6
      }
    ]
  }
}
*/

  String code;
  String message;
  FoodDishModelData data;

  FoodDishModel({
    this.code,
    this.message,
    this.data,
  });
  FoodDishModel.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toString();
    message = json["message"]?.toString();
    data = json["data"] != null ? FoodDishModelData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}
